[package]
name = "dotnet"
version = "0.1.0"
edition = "2024"

[lib]
name = "braillify_native"
crate-type = ["cdylib"]

[dependencies]
braillify = { path = "../../libs/braillify", default-features = false }
